// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type LoginUserInput struct {
	UsernameOrEmail string `json:"UsernameOrEmail"`
	Password        string `json:"password"`
}

type RegisterUserInput struct {
	Username string `json:"username"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type User struct {
	ID       string `json:"_id"`
	Username string `json:"username"`
	Email    string `json:"email"`
}
