// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"

	"github.com/99designs/gqlgen/graphql"
)

type CreateComic interface {
	IsCreateComic()
}

type CreateComicChap interface {
	IsCreateComicChap()
}

type CreateComicSession interface {
	IsCreateComicSession()
}

type Comic struct {
	ID          string          `json:"_id" bson:"_id"`
	CreatedAt   time.Time       `json:"createdAt"`
	UpdatedAt   time.Time       `json:"updatedAt"`
	CreatedBy   *User           `json:"CreatedBy"`
	CreatedByID string          `json:"CreatedByID"`
	Name        string          `json:"name"`
	Description *string         `json:"description"`
	SessionID   []string        `json:"sessionId"`
	Session     []*ComicSession `json:"session"`
	Thumbnail   *string         `json:"thumbnail"`
}

func (Comic) IsCreateComic() {}

type ComicChap struct {
	ID          string         `json:"_id" bson:"_id"`
	CreatedAt   time.Time      `json:"createdAt"`
	UpdatedAt   time.Time      `json:"updatedAt"`
	CreatedBy   *User          `json:"CreatedBy"`
	CreatedByID string         `json:"CreatedByID"`
	Name        string         `json:"name"`
	Description *string        `json:"description"`
	SessionID   string         `json:"SessionID"`
	Session     *ComicSession  `json:"Session"`
	Images      []*ImageResult `json:"Images"`
}

func (ComicChap) IsCreateComicChap() {}

type ComicSession struct {
	ID          string       `json:"_id" bson:"_id"`
	CreatedAt   time.Time    `json:"createdAt"`
	UpdatedAt   time.Time    `json:"updatedAt"`
	CreatedBy   *User        `json:"CreatedBy"`
	CreatedByID string       `json:"CreatedByID"`
	Name        string       `json:"name"`
	Description *string      `json:"description"`
	ComicID     string       `json:"comicID"`
	Comic       *Comic       `json:"Comic"`
	Chaps       []*ComicChap `json:"Chaps"`
	ChapIds     []string     `json:"ChapIds"`
	Thumbnail   *string      `json:"thumbnail"`
}

func (ComicSession) IsCreateComicSession() {}

type CreateComicChapInput struct {
	Name        string  `json:"name"`
	Description *string `json:"description"`
	SessionID   string  `json:"SessionID"`
}

type CreateComicChapInputModel struct {
	Name        string  `json:"name"`
	Description *string `json:"description"`
	CreatedByID string  `json:"CreatedByID"`
	SessionID   string  `json:"SessionID"`
}

func (CreateComicChapInputModel) IsCreateComicChap() {}

type CreateComicInput struct {
	Name        string          `json:"name"`
	Description *string         `json:"description"`
	Thumbnail   *graphql.Upload `json:"thumbnail"`
}

type CreateComicInputModel struct {
	Name        string  `json:"name"`
	Description *string `json:"description"`
	CreatedByID string  `json:"CreatedByID"`
	Thumbnail   *string `json:"thumbnail"`
}

func (CreateComicInputModel) IsCreateComic() {}

type CreateComicSessionInput struct {
	Name        string          `json:"name"`
	Description *string         `json:"description"`
	ComicID     string          `json:"comicID"`
	Thumbnail   *graphql.Upload `json:"thumbnail"`
}

type CreateComicSessionInputModel struct {
	Name        string  `json:"name"`
	Description *string `json:"description"`
	CreatedByID string  `json:"CreatedByID"`
	ComicID     string  `json:"comicID"`
	Thumbnail   *string `json:"thumbnail"`
}

func (CreateComicSessionInputModel) IsCreateComicSession() {}

type DeleteResult struct {
	Success bool   `json:"success"`
	ID      string `json:"id"`
}

type ImageResult struct {
	ID  string `json:"ID"`
	URL string `json:"Url"`
}

type UpdateComicChapInput struct {
	Name        *string `json:"name"`
	Description *string `json:"description"`
}

type UpdateComicInput struct {
	Name        *string         `json:"name"`
	Description *string         `json:"description"`
	Thumbnail   *graphql.Upload `json:"thumbnail"`
}

type UpdateComicInputModel struct {
	Name        *string `json:"name"`
	Description *string `json:"description"`
	Thumbnail   *string `json:"thumbnail"`
}

type UpdateComicSessionInput struct {
	Name        *string         `json:"name"`
	Description *string         `json:"description"`
	Thumbnail   *graphql.Upload `json:"thumbnail"`
}

type UpdateComicSessionInputModel struct {
	Name        *string `json:"name"`
	Description *string `json:"description"`
	Thumbnail   *string `json:"thumbnail"`
}

type UploadFile struct {
	ID   int            `json:"id"`
	File graphql.Upload `json:"file"`
}

type User struct {
	ID       string    `json:"_id" bson:"_id"`
	Comics   []*Comic  `json:"comics"`
	ComicIDs []*string `json:"comicIDs"`
}

func (User) IsEntity() {}
