import type { NextPage } from "next";
import { useEffect, useState } from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { checkAuth } from "../utils/checkAuth";
import { useRouter } from "next/router";

const Home: NextPage = () => {
  const router = useRouter();
  const { data, loading } = checkAuth();
  

  // useEffect(() => {
  //   console.log(data)
  //   window.addEventListener('DOMContentLoaded', () => {
  //     const token = localStorage.getItem('token');
  //     if (token) {
  //       if (data) {

  //         setAuthData(data.Me.username);
  //       }

  //     } else {
  //       router.push('/register');
  //     }
  //   })

  // }, [router]);

  return (
    <div className={styles.container}>
      <Head>
        <title>SharBlock</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {
        loading || (!loading && data?.Me) ? (<p>Loading...</p>) : (<main className={styles.main}>
          <div>
            Hello, <span>{data?.Me.username}</span>
          </div>
        </main>)
      }
      
    </div>
  );
};

export default Home;
