version: "3.6"

services:
  shartube-db:
    container_name: shartube-db
    image: mongo
    networks:
      - shartube-net
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    depends_on:
      - shartube-ws-server
    restart: always

  shartube-comic-server:
    container_name: shartube-comic-server
    networks:
      - shartube-net
    depends_on:
      - shartube-db
      - shartube-user-server
    build: ./comic
    environment:
      - DB_HOST=shartube-db
      - DB_PORT=27017
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - WS_HOST=shartube-ws-server
      - WS_PORT=3012
    env_file:
      - ./comic/.env
    restart: always
    expose:
      - 8080
      

  shartube-user-server:
    container_name: shartube-user-server
    networks:
      - shartube-net
    depends_on:
      - shartube-db
    build: ./user
    environment:
      - DB_HOST=shartube-db
      - DB_PORT=27017
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - WS_HOST=shartube-ws-server
      - WS_PORT=3012
    env_file:
      - ./user/.env
    restart: always
    expose:
      - 8080


  shartube-graphql-gateway:
    container_name: shartube-graphql-gateway
    networks:
      - shartube-net
    depends_on:
      - shartube-comic-server
      - shartube-user-server
    environment:
      - COMIC_SERVER_HOST=http://shartube-comic-server:8080/query
      - USER_SERVER_HOST=http://shartube-user-server:8080/graphql
    build: ./graphql-gateway
    env_file:
      - ./graphql-gateway/.env
    ports:
      - "8080:2100"
    restart: always

  shartube-ws-server:
    container_name: shartube-ws-server
    networks:
      - shartube-net
    build: ./socket
    restart: always
    expose:
      - 3012
    environment:
      - HOST=shartube-ws-server

networks:
  shartube-net:
