FROM node:lts-gallium as ts-compiler
WORKDIR /home/app

COPY . .

RUN yarn install
RUN yarn run build

FROM node:lts-gallium as ts-remover
WORKDIR /home/app

COPY --from=ts-compiler /home/app/package.json ./
COPY --from=ts-compiler /home/app/dist ./

RUN yarn install --production

FROM node:lts-gallium
WORKDIR /home/app
COPY --from=ts-remover /home/app ./
ENV PORT=2100
EXPOSE 2100
CMD ["node","index.js"]